[package]
name = "doc2flow"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[[bin]]
name = "d2f"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4.11", features = ["derive"] }
pulldown-cmark = "0.13.4"
base64 = "0.23"
mime_guess = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true